"use client";

import { useParams } from "next/navigation";
import { createColumnHelper, type ColumnDef } from "@tanstack/react-table";

import { EmptyState, ErrorState, LoadingState } from "@/components/data-display/states";
import { Panel, SectionHeader } from "@/components/data-display/cards";
import { ImportPlanSummary } from "@/components/domain/import-plan-summary";
import { useLocale } from "@/components/layout/locale-provider";
import { PageHeader } from "@/components/layout/page-header";
import { DataTable } from "@/components/tables/data-table";
import { useWorkspaceQuery } from "@/lib/hooks/queries";
import type { ImportEntryPlan, MediaImportPlan } from "@wp2emdash/shared-types";

const entryHelper = createColumnHelper<ImportEntryPlan>();
const mediaHelper = createColumnHelper<MediaImportPlan>();

export default function ImportPlanPage() {
  const { locale } = useLocale();
  const params = useParams<{ projectId: string }>();
  const projectId = params.projectId;
  const { data, isLoading, isError } = useWorkspaceQuery(projectId);

  if (isLoading) {
    return <LoadingState label={locale === "vi" ? "Đang tải kế hoạch import..." : "Loading import plan..."} />;
  }

  if (isError || !data) {
    return (
      <ErrorState
        title={locale === "vi" ? "Không tải được kế hoạch import" : "Unable to load import plan"}
        description={
          locale === "vi"
            ? "Kế hoạch import của dự án này hiện không thể mở."
            : "The import plan for this project is currently unavailable."
        }
      />
    );
  }

  if (!data.snapshot.importPlan) {
    return (
      <EmptyState
        title={locale === "vi" ? "Chưa tạo kế hoạch import" : "No import plan yet"}
        description={
          locale === "vi"
            ? "Hãy chạy dry run trước khi rà soát collection, bản ghi, media import hoặc mapping chưa xử lý."
            : "Run a dry run before reviewing collections, entries, media imports, or unresolved mappings."
        }
      />
    );
  }

  const plan = data.snapshot.importPlan;
  const entryColumns: ColumnDef<ImportEntryPlan, any>[] = [
    entryHelper.accessor("title", {
      header: locale === "vi" ? "Bản ghi" : "Entry",
      cell: (info) => (
        <div className="space-y-1">
          <p className="font-semibold text-slate-900">{info.getValue()}</p>
          <p className="text-xs uppercase tracking-[0.18em] text-muted">
            {info.row.original.sourceType} {locale === "vi" ? "sang" : "to"} {info.row.original.targetCollection}
          </p>
        </div>
      )
    }),
    entryHelper.accessor("slug", { header: "Slug" }),
    entryHelper.accessor("status", { header: locale === "vi" ? "Trạng thái" : "Status" }),
    entryHelper.accessor((row) => row.warnings.length, {
      id: "warnings",
      header: locale === "vi" ? "Cảnh báo" : "Warnings",
      cell: (info) => <span>{info.getValue()}</span>
    })
  ];
  const mediaColumns: ColumnDef<MediaImportPlan, any>[] = [
    mediaHelper.accessor("filename", { header: locale === "vi" ? "Tài sản" : "Asset" }),
    mediaHelper.accessor("mimeType", {
      header: locale === "vi" ? "Loại" : "Type",
      cell: (info) => <span>{info.getValue() ?? (locale === "vi" ? "Không rõ" : "Unknown")}</span>
    }),
    mediaHelper.accessor("url", {
      header: locale === "vi" ? "URL nguồn" : "Source URL",
      cell: (info) => <span className="break-all text-xs text-slate-700">{info.getValue()}</span>
    })
  ];

  return (
    <div className="space-y-6">
      <PageHeader
        title={locale === "vi" ? "Kế hoạch import" : "Import plan"}
        description={
          locale === "vi"
            ? "Rà soát những gì dry run hiện tại sẽ tạo, tải lên và còn để lại ở trạng thái chưa xử lý."
            : "Review what the current dry run would create, upload, and leave unresolved."
        }
        status={data.project.status}
        recommendation={data.project.recommendation}
      />

      <ImportPlanSummary plan={plan} />

      <Panel>
        <SectionHeader
          eyebrow={locale === "vi" ? "Bản ghi" : "Entries"}
          title={locale === "vi" ? "Bản ghi sẽ được import" : "Entries to import"}
          description={
            locale === "vi"
              ? "Các dòng này đến trực tiếp từ kế hoạch do bridge layer tạo ra."
              : "These rows come directly from the plan generated by the bridge layer."
          }
        />
        <div className="p-5">
          <DataTable
            data={plan.entriesToCreate}
            columns={entryColumns}
            searchPlaceholder={locale === "vi" ? "Tìm theo tiêu đề, slug hoặc collection đích" : "Search by title, slug, or target collection"}
            searchValueResolver={(row) => `${row.title} ${row.slug} ${row.targetCollection}`}
          />
        </div>
      </Panel>

      <Panel>
        <SectionHeader
          eyebrow={locale === "vi" ? "Tài sản" : "Assets"}
          title={locale === "vi" ? "Media sẽ được import" : "Media to import"}
          description={
            locale === "vi"
              ? "Các tài sản nguồn đã được nhận diện để đưa vào target integration trong tương lai."
              : "Source assets that have been identified for future target integration."
          }
        />
        <div className="p-5">
          <DataTable
            data={plan.mediaToImport}
            columns={mediaColumns}
            searchPlaceholder={locale === "vi" ? "Tìm theo tên file hoặc URL" : "Search by filename or URL"}
            searchValueResolver={(row) => `${row.filename} ${row.url}`}
          />
        </div>
      </Panel>
    </div>
  );
}
